travis:
  secure:
    BINSTAR_TOKEN: jyzhXpu82RtjRHCwNsiQ3FVb067/kthUAWqfj1d9QKUA56d9YuObKz03q/a0xL/MSwvi7y8twjgyXoPQeZZMf83LQWwdjMo3AJ2U7W0v51WIDayxtqdDF2qe69GjDM0nADP0AGgXsd4QA8kpAiKPOEIZFZwKKxQr5dvXxAw5kEmBVywT++2G0x3jzfp+GcbISnKcRtXQNeEhODOUYWFgyCG2D/bUwULzGuo3NbVAimmnr6cFsDULmv7FIhyYmtiIxQVp0dB7kpxaFtCsZ80IJbJIjuT4FRw+I+b9F1cNHf+WnfdntLUO4RSJqp7p9akpVl2SMLf73Q8xQHzOvptuCeTnNncBbPonUb+aZKSKxJIFfsEi6NGOltwJiZ5T2wW/Yx01tRfsH6maKTXpRXn/Sy6/pI+Ykuc87hWgQssV+yyCBV8b7kr0LalxPDnRtmUBogPbChsgemuGfwlvTEpML0rRYeIlpfuVwndXhWgkluoH8IK5CCxpWsO1uBTCAHmCHQIptH4cXNQliqjcn7UF2hlc3uXijKK7A0AAgX8/u/6dem4jfxdqKWq/e33JVXWBbDmkob9jqCz5bb6q09mM5kzRFWKjbGuMORPMS1y2W2QH/xA7nkCVWUJoeUHoml4aGYyqYJ0kzNS3nekGC/Jdiw6eLM8FhmaKqq1mhDmGQgE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
