travis:
  secure:
    BINSTAR_TOKEN: evlD22dKhnRsrIwwaYplRVTK5Me9yxct/iQZC+NNPP/d0cR8KKXP8KBuykzlUVxs4M11E6Y8kDQvIFakG9asxqg0jkUMtkv3L2zk8PYqff1Odw1irTR3NZ5FI3qs6ZYdDjYEPCu1QkpiQnx5/WGvo6/dIIoDEA8cT625ymhSSw3SIpEiUCRJeYjCRhQSU2YZiMe2u+VpkrrQkgGzcd1AMmrEZYc7nNMoFdgUPyuYKPGVzb+9NHSUcbsnZH+eleGe17YL2DWN5TZ7Vc1zUPjeUoJLRRc9y7C15eTlrIr6WPpeNEL5R7wuV3YCkl7L4/eDBPR9fk/gDT4/YGJ8DkekgxFZTLWu2P9xU4En0kRJ6LuhNgkDFT28LGb6JfUAvPZJp2VlXGZOxOdqsv0IcdPblKhf2RX6Gwmy2YUhEycyEt1LSqQWnxPBPBuzriq4hio+dmDkrUZpTq2kDs3QKHLnkZD8S+OBaFYNzX2ceWgUdcPPh5zM02ZJ5MuYzxEJ0bmHMmJfGne0B4fNHwpYOu8U79VPFiYGBFSnj70b2Af6sWJSJdGs3abtfHUWn6/lX1x7SdpKGRdBIV1m+F5eGEZcBTu+MKaG5UkPK8fDsKog4VH9lZHHbn7onCa9Y8e+bWeCzdh3U4sqnIyqb4YVZLAHQHCAn5GkDKQueUsrCvX0wb4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
